### ISSUE TITLE
Generator loss Interpretation

### ISSUE THREAD

**Issue by KKNakka** [jiamings/wgan#7]
In the standard GAN's, the Generator is optimized in a way that D mistakes a generated sample as a real sample. And the Discriminator output (sigmoid activation) implies the probability of sample coming from Real(1) or generated(0) distribution.

However in WGAN's, losses are defined as: Dloss= D(real)-D(fake), Gloss= D(fake). We minimise both the loss in an alternate fashion with more iterations to critic.  

What does minimising Gloss = D(fake) infers? Since the Output of critic does not imply to any physical quantity.. what does minimising Gloss do?

**Comment by gogameboy1** [comment]
@KKNakka 
The loss in WGAN means the distance between the distribution of the data and the generated. So both the generator and the discriminator try to minimize the loss. However, in the loss function, 
L = E[D(real)] - E[D(fake)], the previous one has nothing to do with the generator. So when updating generator, we only need to consider the -E[D(fake)].
Minimize E[D(fake)] is the same as minimizing -E[D(fake)].

**Comment by upgirlnana** [comment]
Traceback (most recent call last):
  File "wgan_v2.py", line 108, in <module>
    wgan.train()
  File "wgan_v2.py", line 90, in train
    imsave('logs/{}/{}.png'.format(self.data, t/100), bx)
  File "/usr/lib64/python2.7/site-packages/scipy/misc/pilutil.py", line 199, in imsave
    im.save(name)
  File "/usr/lib64/python2.7/site-packages/PIL/Image.py", line 1823, in save
    fp = builtins.open(filename, "w+b")
IOError: [Errno 2] No such file or directory: 'logs/mnist/0.png'
what's wrong  PIL is installed

**Comment by jiamings** [comment]
@upgirlnana You might want to create a `logs` directory yourself.
